apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-server-deployment
  labels:
    app: frontend-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-server
  template:
    metadata:
      labels:
        app: frontend-server
    spec:
      containers:
        - name: frontend-server
          image: robindeclerck/music-frontend
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
          resources:
            limits:
              cpu: 0.2
              memory: "200Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-server
  labels:
    app: frontend-server
spec:
  type: NodePort
  selector:
    app: frontend-server
  ports:
    - name: http
      port: 80
      targetPort: 80